server:
  port: 8001

spring:
  application:
    name: payment-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wyc?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
#  cloud:
##    # consul做注册中心
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: ${spring.application.name}
    # zookeeper做注册中心
#    inetutils:
#      timeout-seconds: 10
#    zookeeper:
#      connect-string: localhost:2181

# eureka做注册中心
eureka:
  instance:
    # 修改一下实例ID名称
    instanceId: ${spring.application.name}:${random.value}
    # 显示实例IP信息
    prefer-ip-address: true
    # 心跳时间间隔
    lease-renewal-interval-in-seconds: 1
    # 服务端收到最后一次心跳等待的时间上限，超时剔除服务
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://xuefei:xuefei@localhost:7901/eureka/


mybatis:
  #  对应的sql映射
  mapper-locations: classpath:mapper/*.xml
  #  type-aliases-package:

# 显示sql日志
logging:
  level:
    com.xuefei.dao: debug