server:
  port: 801

spring:
  application:
    name: order-consumer
#  cloud:
#    # consul做注册中心
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: ${spring.application.name}
    # zookeeper做注册中心
#    inetutils:
#      timeout-seconds: 10
#    zookeeper:
#      connect-string: localhost:2181


eureka:
  instance:
    # 修改一下实例ID名称
    instanceId: ${spring.application.name}:${random.value}
    # 显示实例IP信息
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://xuefei:xuefei@localhost:7901/eureka/

feign:
  client:
    paymentname: payment-provider
    config: # 该配置与hystrix配置，如果都配置情况下，以时间小的为准
      default: # 默认所有项目
        # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 5000
        # 指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 60000
  hystrix:
    # 让openFeign可以使用hystrix进行服务降级
    enabled: true

#设置Hystrix的超时时间 10秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# 设置feign监控级别
logging:
  level:
    com.xuefei.feign: debug
