server:
  port: 7902

spring:
  application:
    name: eureka
  security:
    user:
      name: xuefei
      password: xuefei

eureka:
  instance:
    hostname: localhost
    # 修改一下实例ID名称
    instanceId: ${spring.application.name}:${random.value}
    # 显示实例IP信息
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    # 设置服务注册中心url
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:7901/eureka/,
        http://${spring.security.user.name}:${spring.security.user.password}@localhost:7902/eureka/
  server:
    # 关闭自我保护模式，关闭后只要没收到客户端心跳，那么立马剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000

